name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: nuget restore src/SoxSharp.sln
    - name: Run a one-line script
      run: msbuild "src\SoxSharp.sln" /verbosity:minimal
